default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: pharma_dashboard_development

test:
  <<: *default
  database: pharma_dashboard_test

production:
  <<: *default
  database: pharma_dashboard_production
  username: your_production_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
